name: Create installable ZIP-Packages of Themes
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Build Themes-Packages
      CI_COMMIT_AUTHOR: fruithost | Themes Builder
    steps:
    - uses: actions/checkout@v3

    # Build steps
    - uses: actions/setup-node@v3
      with:
        node-version: '22'
    - name: Node Install
      run: cd ./.builder/ && npm install
    - name: Node Build
      run: cd ./.builder/ && node ./build.js

    # Commit and push all changed files.
    - name: Commit changes
      if: github.event_name == 'push'
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "fruithost@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
